version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: git-shame-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: git-shame
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db:
    image: node:20
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git-shame?schema=public
    command: >
      bash -c "npm install node-pg-migrate pg &&
              npx node-pg-migrate up"

volumes:
  postgres-data:
